language: shell
sudo: required
services:
- docker
before_install:
#- openssl aes-256-cbc -K $encrypted_f415018e36c0_key -iv $encrypted_f415018e36c0_iv
#  -in ./travis/travis_github_deploy_key.enc -out travis_github_deploy_key -d
- docker build -t ensign .
#- sudo apt-get update && sudo apt-get install -y git live-build curl coreutils vim
#- sudo mkdir -p /opt/live
#- sudo cp -r * /opt/live
script:
- docker run --privileged --cap-add SYS_ADMIN --name=ensign ensign
- docker container cp ensign:/opt/live/live-image-amd64.hybrid.iso ./
#- sudo /opt/live/build.sh
after_install: 
deploy:
  provider: releases
  api_key:
    secure: GNTr2FLGXr2zsAZqEx75OCs9SnsKHVGLGCODgGWUYHpv6LtPxYHWDFbcDH7vXzc3D7kuJpd/6dnZ0dI37SSvnEFxFQxL2aChoDYqQTc4RnpNti9yO7aQv4p0tcXImot0MakvKyOxtU+BCKrp/aMYpPk1abrrapvy312tXqnVqu1K4/M+pS5lGMowMtisCUB552k5XJi1I4Yxr44PoT8J705yZZeJ9Z8n24RiPbl7gNYp7SHQHACZ2Yntqayppfoze1P/tiNQ13TUSWdiQMXh7b3aDJG3P/VOzehCsP7g7/3wVVRO1XWphZlAHJeZZJ+2d5ysKtwHxkrWBjWa1MVHYbZ6ubMpM/Xg5WuHluDZDbE1DYe3yKsNoSUP8xjvTjTsCCviMjJtvIM2SAGjeR8aNImMMnJgNnyfEt/Iknof4EAjp6aEx0kWJLpFhUS+7sWZOP3c7E6MKa98S6i+ZgqiOgfm8SSMfshPMYJJ74bq7YluSsZ4Ek5EwgCQEfJT3WNa4E60eY02vTbcsohqA+7WaSq0sJov8Ei+gMR8oCUqzhavK0Hyqd+/RLp/vWAzs4GBum46cahgZ69wKRq/d7Umw4HRrAgASmzs2keHAG50By04t4gwvhwWjmUl1FqhppHytgnRbNx3Qw5kafAriQbnzl7mvNya7bF9lQR4u4RzrC4=
  file: live-image-amd64.hybrid.iso
  on:
    repo: KeenWill/ensign
    #tags: true
    all_branches: true
