sudo: required
services:
- docker
before_install:
- docker build -t ensign .
script:
- docker run --privileged --name=ensign ensign
- docker container cp ensign:/opt/live/live-image-amd64.hybrid.iso ./
after_install:
deploy:
  provider: releases
  file: build.sh
  on:
    repo: KeenWill/ensign
    all_branches: true
    tags: true
