language: shell
sudo: required
services:
- docker
before_install:
- docker build -t ensign .
#- sudo apt-get update && sudo apt-get install -y git live-build curl coreutils vim
#- sudo mkdir -p /opt/live
#- sudo cp -r * /opt/live
script:
- docker run --privileged --cap-add SYS_ADMIN --name=ensign ensign
- docker container cp ensign:/opt/live/live-image-amd64.hybrid.iso ./
#- sudo /opt/live/build.sh
after_install: 
deploy:
  provider: releases
  api_key:
    secure: bo7akH8tVl83yTWRQEatfEYf9iRFfb16H5DrFekUYMCe1b5kYi2X7Talfyusu1e9WoC1oshMPoK5Axp9UxnNCrma1lUmd2KINHc8EwZqMknKvePb4Gc1L+20YvzJsaFcSwHs188t3rlFe1dxYw4dY2RGMhW6RwznEsB9Jg4VOE7cYayoZ8+BWhs68YrbFzV/iLySyHx7Ejdd64AyKg4H6oRMm+t0Wb5W5Cs9VTsC1cRi/e8Z6WpTqMBKQjHM+kvUfpyFDIaYbx1fXA6a42Lr3dz73Jur2b9SCh2FKWTnta3Jo+fDYgnmpUQu+vYL2UDtK6PJZLNqrwoywEQrKduRJivwnPtuSsnt7IUKPxqmz1nE8CAvNR6ohwnha7iWTSNxPoBeNSVzY/aRUzT8oxAPhSIRbyPFDJnoTbOyhPNE5CXLDUmCgUFV/hIBphCW6K+/JKHte9qnOwrJHmwEAxFQ70cndSBqA4E5WhSQ6MJ4oM/7ZjSG89exiv3SweqMY8m8Hn2OyhkrnYTUZAjUd5Q6dy74VcjDX0t/XpTRNhpKl+c56Fzx4f8+AsMK42Fj12d6zgdolhBjMcgOhPMTXoZgwkeutkRj3zL23GIp2FNjSCAqoxUgHd92ugwrB1BH4IXFPHYFv3tL43P2Fj9YzUr0dpnLM1vYyePgUkpJdWi0lXg=
  file: live-image-amd64.hybrid.iso
  username: KeenWill
  overwrite: true
  skip_cleanup: true
  on:
    repo: KeenWill/ensign
    #tags: true
    all_branches: true
