#!/bin/sh
set -e
lb config noauto \
	--mode debian \
	--architectures amd64 \
	--linux-flavours amd64 \
	--debian-installer false \
	--archive-areas "main contrib non-free" \
	--apt-indices false \
	--apt-recommends false \
	--memtest none \
	--bootappend-live "boot=live components username=root hostname=ensign" \
	--iso-application "Ensign Linux" \
	--iso-publisher "Ensign" \
	--iso-volume "Ensign Live" \
	--debootstrap-options "--variant=minbase" \
	--firmware-chroot false \
	--initsystem systemd \
	#--bootappend-live "boot=live components persistence persistence-encryption=luks"
	"${@}"